# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeChronicle < Formula
  desc "Terminal dashboard for navigating, searching, and monitoring Claude Code activity"
  homepage "https://thinkwright.ai/clog"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_amd64.tar.gz"
      sha256 "6a6c4ed3310b7d71baa822f663c1c55259f485bb2218199ea538abb3f02558d0"

      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_arm64.tar.gz"
      sha256 "741dff3a1aa3543cd97f7ba9b995d6b613da0ce7f97d2f1a9875a53a34530216"

      def install
        bin.install "clog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_amd64.tar.gz"
      sha256 "3606a68b0e6a6948ae5bce08f83cff513c6000057a353f4cef594356892950da"
      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_arm64.tar.gz"
      sha256 "5e9c6d9efb28d0dc1b8cdf97b9fb499d81cdcad293ee439d89e1455cce32e043"
      def install
        bin.install "clog"
      end
    end
  end
end
