# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeChronicle < Formula
  desc "Terminal dashboard for navigating, searching, and monitoring Claude Code activity"
  homepage "https://thinkwright.ai/clog"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_amd64.tar.gz"
      sha256 "e0a5583a19755e4b85194bcc5e34f171456bf44437dc2a4a072e79e4110e8a8f"

      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_arm64.tar.gz"
      sha256 "065fb8d875fd2c813b1caf545fb9d5e510d1c253be4138c9b9ccf59efd130d9e"

      def install
        bin.install "clog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_amd64.tar.gz"
      sha256 "f33aa877c074f730efbf79354a06c80575aa4564bc1f71eb79ee1dd383cd687c"
      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_arm64.tar.gz"
      sha256 "4858f27f6253214deb59cdf77497549648f308a3f687213a8c91fea21973d206"
      def install
        bin.install "clog"
      end
    end
  end
end
