# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeChronicle < Formula
  desc "Terminal dashboard for navigating, searching, and monitoring Claude Code activity"
  homepage "https://thinkwright.ai/clog"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_amd64.tar.gz"
      sha256 "37d2406750c08955a9b5f09e350e7ed189ef0f9df296d628c784b9380e8bea29"

      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_arm64.tar.gz"
      sha256 "89defdbb2b98e4627bebc729d4b2a85d12d6a7530d9c20871422a56498eabc66"

      def install
        bin.install "clog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_amd64.tar.gz"
      sha256 "61284bc01d133f016dd6e45ce603da4607b263072c6aeecd35c6c6b6415b86e2"
      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_arm64.tar.gz"
      sha256 "47b2eaf331f83c9277a36037d6daffa7532c165dad5e7bbc3f9e09c52fb35d3e"
      def install
        bin.install "clog"
      end
    end
  end
end
