# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clog < Formula
  desc "Terminal dashboard for navigating, searching, and monitoring Claude Code activity"
  homepage "https://thinkwright.ai/clog"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_amd64.tar.gz"
      sha256 "6391c980ead07080b7293863c70fdc95112a939549d75fd7cfedfd137a3372a5"

      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_darwin_arm64.tar.gz"
      sha256 "c147d613cdae5e7de6a6b2953da885151b373a77119eead620d6c3b83d43ef88"

      def install
        bin.install "clog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_amd64.tar.gz"
      sha256 "a755f4a04d8095824a60464c22c5950c1be8772eda8156163e88d8fafe435643"
      def install
        bin.install "clog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thinkwright/claude-chronicle/releases/download/v0.1.0/claude-chronicle_linux_arm64.tar.gz"
      sha256 "8725371e0ad23b7611748fb7e8ae868d92a02aadf951e860ef4e7c40be2894c2"
      def install
        bin.install "clog"
      end
    end
  end
end
