# This file was generated by GoReleaser. DO NOT EDIT.
cask "threadmark" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f19f2bfdaf1625b2a653d54893c08d00b2f45e010b849a0c4ae4343318ada6e4"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6846b1df6498dceaa4b8951652896f0a2d8bd7e1bcfb7b273b3abeffafce0c0"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ba459b4d6620c77ac3db0efdaca9566fc94ad87306e2784aa3d6154fcc00776"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a6b025efe2978056e15233b54edcab4caf996a3aaf34f8f368330aa56543116"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_linux_arm64.tar.gz"
    end
  end

  name "threadmark"
  desc "Local handoff and continuity for Claude Code, Codex, and AI coding agents"
  homepage "https://github.com/thinkwright/threadmark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "threadmark"
  binary "threadmarkd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/threadmark"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/threadmarkd"]
    end
  end

  # No zap stanza required

end
