# This file was generated by GoReleaser. DO NOT EDIT.
cask "threadmark" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "88496015528bdff8fc895c36eb86cedec8a54db0b7d58e8b6eee0edeb6a2d331"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "116de849d981839f7a9bab385b2cc11ce1b3d449bf9067f4e4413153eea5d6ed"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16bf2c2a9fc0cab1f2d252924dc7a529e80099c2646a023eb664cfdb16495c69"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bbb1e6711000ad63b7854ea5aa0d06be6c3b8595d379aeee8dbf57e21af4091"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_linux_arm64.tar.gz"
    end
  end

  name "threadmark"
  desc "Local handoff and continuity for Claude Code, Codex, and AI coding agents"
  homepage "https://github.com/thinkwright/threadmark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "threadmark"
  binary "threadmarkd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/threadmark"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/threadmarkd"]
    end
  end

  # No zap stanza required

end
