# This file was generated by GoReleaser. DO NOT EDIT.
cask "threadmark" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "0503bc4f3ee55c969faef02ecbb1855447a72a60cc770bcdffdefdf6f3257fb8"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "65bf60724179abd45f2679884cc2c559da7fd5e56f80909ce472d8caa8af4fea"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92d0e96662f96fcc3625f42e9848eaab405924665732c87f2873e4fccaca9e60"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd627c18a8be7e112533f3b8d91da29f6edc7f507a259dc7e6a7b87f23791a04"
      url "https://github.com/thinkwright/threadmark/releases/download/v#{version}/threadmark_linux_arm64.tar.gz"
    end
  end

  name "threadmark"
  desc "Local handoff and continuity for Claude Code, Codex, and AI coding agents"
  homepage "https://github.com/thinkwright/threadmark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "threadmark"
  binary "threadmarkd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/threadmark"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/threadmarkd"]
    end
  end

  # No zap stanza required

end
